"""added cascade del

Revision ID: 0f0bf4cafec1
Revises: 60094f903fc4
Create Date: 2022-09-26 20:01:06.243641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0bf4cafec1'
down_revision = '60094f903fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_ibfk_4', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_ibfk_5', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'roles', ['roleId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_ibfk_5', 'user_role', 'roles', ['roleId'], ['id'])
    op.create_foreign_key('user_role_ibfk_4', 'user_role', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
