"""dodao cascade delete OPET

Revision ID: 78e81d281862
Revises: 3865b2a09cf4
Create Date: 2023-01-19 12:39:53.482686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e81d281862'
down_revision = '3865b2a09cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_product_ibfk_1', 'order_product', type_='foreignkey')
    op.create_foreign_key(None, 'order_product', 'products', ['productId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_product', 'orders', ['orderId'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_category_ibfk_2', 'product_category', type_='foreignkey')
    op.drop_constraint('product_category_ibfk_1', 'product_category', type_='foreignkey')
    op.create_foreign_key(None, 'product_category', 'categories', ['categoryId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_category', 'products', ['productId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.create_foreign_key('product_category_ibfk_1', 'product_category', 'categories', ['categoryId'], ['id'])
    op.create_foreign_key('product_category_ibfk_2', 'product_category', 'products', ['productId'], ['id'])
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_ibfk_1', 'order_product', 'orders', ['orderId'], ['id'])
    # ### end Alembic commands ###
