"""dodat korisnik u Order

Revision ID: b2fcede82d52
Revises: b18089cc286a
Create Date: 2023-01-17 14:11:00.702023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fcede82d52'
down_revision = 'b18089cc286a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('userEmail', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'userEmail')
    # ### end Alembic commands ###
